## Decision Analysis Project 1
Authors:
* Sebastian Chwilczynski 148248
* Karol Cyganik 148250

### Data set
1. What is the domain of the problem about?

    Ranking of universities on different criteria
2. What is the source of the data? 
   
   [The main source of the data is perspektywy ranking of IT related studies of Polish universities](https://ranking.perspektywy.pl/2022/ranking/ranking-studiow-inzynierskich/informatyka-inz). We selected only these attributes that were relevant to the Decision Maker (gain type). Criteria description can be found [here](https://ranking.perspektywy.pl/2022/article/metodologia-rankingu-kierunkow-studiow-2022r). Additionally we added two cost type criteria: `distance` calculated with google maps and `acceptance threshold` using [this website](https://dostanesie.pl/kierunek/informatyka#perPage=100&page=1&sortBy=%22ThresholdDesc%22). We do not show names of universities but rather we gave them `id` - uppercase letters, so we omit some biases. Location from which we checked the distance was some small village in Poland.
3. What is the point of view of the decision maker?
    
    Our decision maker is a high school graduate - Tom, who wonders which university too chose from. He wants to study Informatics and asked us about advice. His preferences are as follows:
    * He wants to be back at home once a month, so the lesser the distance from his hometown the better. However, it is not the most important attribute to him.
    * Tom wants to become a researcher and he wants to work in an international research team. So it is quite important to him that university he will study at does a lot of research with foreign scientists. For the same reason citations in TOP10 journals are important to him.
    * He doesn't care that much about the ranking given by other professors. Also economics after graduation are not that important to him as he knows exactly what he wants to do and knows expected salary. Moreover economic situation may change since we are in quite unstable situation.
    * Tom wants to study with good students around him to work together on projects.
    * He did quite well on A-levels but after checking thresholds he is not sure if he will be accepted to all universities in Poland. So he prefers universities with smaller thresholds, but weight is very small.
  
4. What is the number of alternatives considered? Were there more of them in the original data set?
   
   We took top 20 universities. In original dataset there were much more.

5. Describe one of the alternatives considered (give its name, evaluations, specify preferences for this
alternative)

    Let it be university `I` which obtained:
    * 22.6 points on evaluation by academic staff. Not that important to DM
    * 84.9 on economic situation of the graduate. Not that important
    * 46.8 score on publications in TOP 10 journals. Not the best score on important one
    * 90.4 obtained on quality of accepted students. Very prefferable one.
    * 66.2 as a result of the research with foreigner scientists. Not bad.
    * 413 distance from hometown. Quite far away actually. Not good
    * 0.785 threshold, where maximum is 1. Tom should get there easily.
6. What is the number of criteria considered? Were there more of them in the original data set?

    We consider 7 criteriaa 5 of which are taken from `perspektywy` ranking, 2 are handmade by use. There are much more criteria in `perspektywy` ranking.
7. What is the origin of the various criteria? (catalog parameter / created by the decision maker - how?)
    
        Already answered at point `2`
        
8. What are the domains of the individual criteria (discrete / continuous)? Note: in the case of continuous
domains, specify the range of the criterion’s variability, in the case of others: list the values. What is
the nature (gain / cost) of the individual criteria?
    * `WSK ocena p. kadre` continuous [0,100] gain type
    * `ekonom. losy absolw.` continuous [0,100] gain type
    * `jak. przyj. na studia` continuous [0,100] gain type
    * `TOP 10` continuous [0,100] gain type
    * `pub. we wspl. zagr.` continuous [0,100] gain type
    * `distance` continuous (integers) [56, 580] cost type
    * `threshold` continuous [0,1] cost type. Different universities has different range of maximum points so it was obtained by dividing theshold by maximum number of points

9. Are all criteria of equal importance (should they have the same ”weights”)? If not, can the relative
importance of the criteria under consideration be expressed in terms of weights? In this case, estimate
the weights of each criterion on a scale of 1 to 10. Are there any criteria among the criteria that are
completely or almost invalid / irrelevant? `No`, every criteria have different weights:
   * `WSK ocena p. kadre` 5
   * `ekonom. losy absolw.` 5
   * `jak. przyj. na studia` 10
   * `TOP 10` 7
   * `pub. we wspl. zagr.` 7
   * `distance` 3
   * `threshold` 1
  
    Every criterion is relevant as we selected them with the help of DM.

10. Are there dominated alternatives among the considered data set? If so, present all of them (dominating
and dominated alternative), giving their names and values on the individual criteria.

    first 5 criteria and threshold are contradicting with one another so there is no dominance relation. Moreover distance is not correlated at all with other values so it also is againts dominance of any alternative

11. What should the theoretically best alternative look like in your       opinion? Is it a small advantage on
many criteria, or rather a strong advantage on few (but key) criteria? Which?

    Best alternative should be very strong in the 3 most important criteria w.r.t weights. Other criteria, probably will decide about the order between the best ones. 

12.  Which of the considered alternatives (provide name and values on individual criteria) seems to be the
best / definitely better than the others? Is it determined by one reason (e.g. definitely the lowest
price) or rather the overall value of the criteria? Does this alternative still have any weaknesses?
    
`M` seems strong with scores:
* `WSK ocena p. kadre` 100
* `ekonom. losy absolw.` 99.2
* `jak. przyj. na studia` 100.0
* `TOP 10` 48.9
* `pub. we wspl. zagr.` 51.0
* `distance` 188
* `threshold` 0.965

It obtained the best score on the most important attribute. It's not the best in Top 10 and pub. we wspl. zagr. but on the first 2 it is again the best. It is the weakest regarding the threshold but it has small importance.

13. Which of the considered alternatives (provide name and values on individual criteria) seems to be the
worst / definitely worse than the others? Is it determined by one reason (e.g. definitely the highest
price), or rather the overall value of the criteria? Does this alternative still have any strengths?

It looks like `U` may be the worst:
* `WSK ocena p. kadre` 1.7
* `ekonom. losy absolw.` 56.1
* `jak. przyj. na studia` 54.8
* `TOP 10` 27.0
* `pub. we wspl. zagr.` 25.5
* `distance` 580
* `threshold` 0.39

It seems to be very bad in first 5 attributes compared with other universities. Moreover it is so far away. However, the threshold of it is not that bad so from the perspective of person who wrote A levels not that well it may be actually a good choice.


In [3]:
from mcda.promethee import PrometheI, PrometheII
import numpy as np

alternatives = np.array(
        [
            [98, 8, 400],
            [58, 0, 800],
            [66, 5, 1000],
            [74, 3, 600],
            [80, 7, 200],
            [82, 10, 600],
        ]
    )
alternatives_names = ["ITA", "BEL", "GER", "SWE", "AUT", "FRA"]

thresholds = {
        "q": np.array([0, 0, 100]),
        "p": np.array([0, 2, 300])
}

preference_types = np.array([1, 1, -1])  # 1 for gain and -1 for cost
weights = np.array([3, 2, 5])
solver = PrometheI()
print(solver.solve(alternatives, preference_types,
                       thresholds, weights, alternatives_names))

[['ITA', 'AUT'], ['FRA'], ['SWE'], ['BEL', 'GER']]


In [4]:
solver = PrometheII()
print(solver.solve(alternatives, preference_types,
                       thresholds, weights, alternatives_names))

['ITA', 'AUT', 'FRA', 'SWE', 'GER', 'BEL']


In [5]:
from mcda.electretrib import ElectreTriB
alternatives = np.array(
    [
        [90, 86, 46, 30],
        [40, 90, 14, 48],
        [94, 100, 40, 36],
        [78, 76, 30, 50],
        [60, 60, 30, 30],
        [64, 72, 12, 46],
        [62, 88, 22, 48],
        [70, 30, 12, 12],
    ]
)

profiles = np.array(
    [
        [64, 61, 32, 32],
        [86, 84, 43, 43],
    ]
)

thresholds = {
    "q": np.array(
        [
            [2, 2, 0, 0],
            [3, 2, 0, 0]
        ]),
    "p": np.array(
        [
            [6, 5, 2, 2],
            [7, 8, 2, 2]
        ]),
    "v": np.array([
        [20, 24, np.nan, np.nan],
        [20, 25, np.nan, np.nan]
    ])
}

preference_types = np.array([1, 1, 1, 1])  # 1 for gain and -1 for cost
weights = np.array([0.4, 0.3, 0.25, 0.05])
cred_th = 0.65
solver = ElectreTriB()
print(solver.solve(alternatives, preference_types,
                   thresholds, profiles, weights, cred_th, "pessimistic"))

print(solver.solve(alternatives, preference_types,
                   thresholds, profiles, weights, cred_th, "optimistic"))


[3 1 3 2 1 2 2 1]
[3 2 3 2 1 2 2 2]


In [6]:

from mcda.srf import SRF
srf = SRF()
srf.solve(10, 5, [2, 0, 3, 1])


[0.36363636 0.29818182 0.16727273 0.13454545 0.03636364]
